FROM node:10.15.1
ARG APP_DIR=/var/www
ARG LOCAL_APP_PATH=app/server
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}
COPY ${LOCAL_APP_PATH}/package*.json ./
RUN npm i
COPY . .
EXPOSE 4000
CMD ["npm", "run", "prod"]
