FROM node:10.15.1
ARG APP_DIR=/var/www
ARG LOCAL_APP_PATH=app/frontend
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}
COPY ${LOCAL_APP_PATH}/package*.json ./
RUN npm i
COPY . .
EXPOSE 3000
CMD ["npm", "run", "docker-prod"]
